### ISSUE TITLE
If I call getProducts, getSubscription, there is an error.

### ISSUE THREAD

**Issue by cddceo** [dooboolab-community/react-native-iap#2776]
Current Version : "react-native-iap": "12.14.1"

This error is not found in the previous version of "react-native-iap": "12.12.2". The error appears only in IOS.
![Simulator Screenshot - iPhone 15 Plus - 2024-06-19 at 10 05 14](https://github.com/dooboolab-community/react-native-iap/assets/76676886/c91b3e25-f1ab-4136-a5bb-ab455a07c800)

Step:
1. call getProducts
2. call getProducts or getSubscriptions
3. error

I can make a code that calls getProducts only once, but I have to call getSubscription as well.

**Comment by janisievins** [comment]
I'm facing the same error after updating React Native from 0.71.13 to 0.74.2.
react-native-iap version (12.13.0) and its implementation remained unchanged. Everything was working fine before updating React Native.

**Comment by hyochan** [comment]
@arthurgeron Could you kindly follow up this issue? Looks like related to #2777 2518

**Comment by devartwa** [comment]
I'm having the same issue using the latest version of iap and react-native

**Comment by hdsuperman** [comment]
In order to display the price information of the subscription page first, I called getSubscriptions after the app started, and called getSubscriptions again to update the data when entering the premium page. However, the same problem occurred as long as it was called twice. There was no problem if it was called only once.

**Comment by arthurgeron** [comment]
> 2\. getSubscriptions

Have you waited for the resolution of the first Promise before calling `getSubscriptions` or `getProducts` again?

**Comment by arthurgeron** [comment]
> I just deleted this parts. But It's not good method.
> 
> //reject ("E_CANCELED", "Previous request was canceled deue to a new request", nil) in node_modules/react-native-iap/ios/LatestPromiseKeeper.swift is deleted and used.
> 
> There seems to be no problem with other movements.

That only leaves the previous promise hanging infinitely, the error is on purpose. You're not meant to make these calls in parallel, a new call will override the data from the previous invocation.

**Comment by arthurgeron** [comment]
@hyochan ,

We have a few options to consider:

1. Allow parallel calls: This could lead to multiple renders and potential issues, such as an older promise resolving after a more recent one.
2. Resolve canceled promises: Instead of rejecting them, we could resolve them since they don't return data anyway. However, this might be confusing in some scenarios as it results in a falsy promise resolution and could be considered an anti-pattern.
3. Improve documentation: We can enhance the documentation to clarify this behavior.   

If you agree with the changes I've described in #2604, which includes rejecting canceled promises, I suggest we focus on updating the documentation. Changing coding patterns and behaviors solely due to user confusion might not be practical and could introduce more bugs.

**Comment by arthurgeron** [comment]
There's indeed a bug, I'm working on a fix!
