### ISSUE TITLE
Build Error After Upgrading to targetSDK 34

### ISSUE THREAD

**Issue by haresh4d** [dooboolab-community/react-native-iap#2782]
I am getting following build error in android after upgrading to targetSDK 34

`Failed to transform billing-ktx-7.0.0.aar (com.android.billingclient:billing-ktx:7.0.0) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.`

**Comment by hyochan** [comment]
Could you try updating your build.gradle file like below?

```
// In your root build.gradle file
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:7.0.0' // or a compatible version
    }
}

// In your gradle-wrapper.properties file
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0-bin.zip // or a compatible version
```

Also try to clean and rebuild
```
./gradlew clean
./gradlew build
```

If the issue persists, we need additional information to accurately diagnose the cause. Please provide the following details:

- PC environment (operating system, version, etc.)
- Information about the Android device you are using
- React Native version
- List of other dependencies in the project

Providing this information will help us diagnose and resolve the issue more precisely.

**Comment by tien271** [comment]
@Girum upgrade minSdkVersion to 24

**Comment by chichilatte** [comment]
> @Girum upgrade minSdkVersion to 24

This worked for me where nothing else would, thank you. What a shame to lose users with old devices! Google's treadmill of progress is crap for poorer users and the planet, imho.

**Comment by steven-sh** [comment]
I encountered this problem too, and I'd like to keep my minSdkVersion at 21 so I looked a little further and found this:

https://stackoverflow.com/questions/78113826/failed-to-transform-firebase-auth-22-3-1-aar/78149818#78149818

I added the following two lines to my debug build type in /android/app/build.gradle:

```
...
buildTypes {
        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
...
```

but I found that I was getting crashes on startup due to the obfuscation.  I was able to fix it by adding the following line to /android/app/proguard-rules.pro:

`-keep class com.facebook.** {*;}`

I'm still not happy with the solution since I don't really want obfuscated code in debug builds and also there must be some react-native proguard rules that are getting picked up in release builds but not debug builds that I should be tapping into rather than the blanket keep I'm using here, but I thought I'd post this in case anyone else is having issues.

**Comment by hardik-wts** [comment]
I have face same issue when I have installed 
`"@react-native-google-signin/google-signin": "^13.1.0",` in `react-native`

need to update the config as below 

open `android/build.gradle`

`
buildscript {
 ext {
    minSdkVersion = 24
    compileSdkVersion = 34
    targetSdkVersion = 34
 }
}
`
